### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by philipnewcomer** [Pilothouse-App/pilothouse#30]
I need to change the name of the project. http://wpdocker.com/ is already an established commercial entity, and I don't want to cause confusion with that, or to be using a name they may have trademarked. 

When I originally named the project, I did a Google search for `wpdocker` and didn't see any relevant results, so I assumed no one was using the name. What I didn't notice was that Google oh-so-helpfully changed my search query to "wplocker", thus I didn't see wpdocker.com in the search results.
![screen shot 2017-01-05 at 8 14 14 am](https://cloud.githubusercontent.com/assets/1446874/21681847/1eea6656-d31f-11e6-9a24-3e6a1d9d0c97.png)

So, I've settled on "DockerBox" as the new name of the project. This more accurately reflects the goal of the project to be a more generic local development environment using Docker, useful not only for WordPress projects, but general PHP projects as well.

As part of this ticket, I will be updating all instances of `wpdocker` in the codebase to `dockerbox`. I own the DockerBox GitHub organization, and will be moving this repository to https://github.com/dockerbox/dockerbox shortly. GitHub will redirect the old repository URLs, and all Git history, issues, etc. will be retained. Users will still be able to `clone`, `fetch`, and `push` to https://github.com/philipnewcomer/wpdocker as GitHub will redirect those requests to the new location (https://help.github.com/articles/renaming-a-repository/).

**Comment by AaronHolbrook** [comment]
👍

**Comment by AaronHolbrook** [comment]
What will the bash command be? dockerbox?

**Comment by philipnewcomer** [comment]
Yes, `dockerbox` will be the new bash command. It's also worth noting that the xdebug ide key will be `dockerbox` as well, so be sure to update that in your projects.

**Comment by philipnewcomer** [comment]
Repository has been successfully moved to https://github.com/DockerBox/dockerbox

**Comment by philipnewcomer** [comment]
Reopening to change name to Pilothouse (#44)

**Comment by philipnewcomer** [comment]
For future reference, instructions for upgrading from DockerBox to Pilothouse without losing data are here: https://github.com/Pilothouse-App/pilothouse/wiki/Upgrading-from-DockerBox-to-Pilothouse
