### ISSUE TITLE
Customize value: php memory size

### ISSUE THREAD

**Issue by AaronHolbrook** [Pilothouse-App/pilothouse#40]
Currently working on a project that requires a large overhead of memory available. Need to be able to set this pretty high (higher than we'd want for a default, I'm sure)

**Comment by philipnewcomer** [comment]
You can now customize any PHP configuration setting, and not only PHP, but any service in Pilothouse. Documentation here: https://github.com/Pilothouse-App/pilothouse/wiki/How-to-Override-Service-Configuration-Files
