### ISSUE TITLE
Have wp-cli respect local .wp-cli/config.yml file

### ISSUE THREAD

**Issue by AaronHolbrook** [Pilothouse-App/pilothouse#43]
http://wp-cli.org/config/

Any way to have it respect the host's preferences here?

**Comment by philipnewcomer** [comment]
@AaronHolbrook I'm pretty sure that's possible, but would a, say, `wp-cli.yml` file placed in the dockerbox directory work just as well? Having it in that location would keep all configuration contained within dockerbox, which I think would be preferable.

**Comment by AaronHolbrook** [comment]
True, what if you looked in both and you prioritized a `wp-cli.yml` that's within dockerbox?

I.e. the normal user location is the fallback - that way you get best of both worlds, and people that may not want to have duplicate customization folders don't have to

**Comment by philipnewcomer** [comment]
Added WP-CLI to the config file documentation: https://github.com/Pilothouse-App/pilothouse/wiki/How-to-Override-Configuration-Files
