### ISSUE TITLE
env: can't execute 'tput': No such file or directory

### ISSUE THREAD

**Issue by philipnewcomer** [Pilothouse-App/pilothouse#51]
Warning message is displayed before the output of some WP-CLI commands, like `wp plugin list`

**Comment by markuswolff** [comment]
You are most probably running WP-CLI in a minimal Linux environment that is missing the tput command. Install the ncurses package and the message should disappear.

**Comment by philipnewcomer** [comment]
@markuswolff you're right, WP-CLI is being run in a very minimal Alpine Linux container. I'll see if installing ncurses fixes the issue. Thanks for pointing me in the right direction!

**Comment by philipnewcomer** [comment]
Yup, looks like that did the trick. Thanks again @markuswolff.
