### ISSUE TITLE
Issue with InnoDB redo log size.

### ISSUE THREAD

**Issue by Jaace** [Pilothouse-App/pilothouse#52]
Putting this here in case it's a setup issue - I'm importing a rather large database at around 4.0 Gb and got this error that I'm looking into. Perhaps it's a system level issue, but figured I'd point this out in case anyone else has run into this problem:
```
2017-02-25 23:07:21 140083114277632 [ERROR] InnoDB: The total blob data length (10709816) is greater than 10% of the total redo log size (100663296). Please increase total redo log size.
```

After logging into mysql and running the following, it looks like we have approximately 268 Mb allocated here.

```
pilothouse compose exec mysql /usr/bin/mysql -u root -proot
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7
Server version: 10.1.21-MariaDB-1~jessie mariadb.org binary distribution

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SELECT @@innodb_buffer_pool_size;
+---------------------------+
| @@innodb_buffer_pool_size |
+---------------------------+
|                 268435456 |
+---------------------------+
1 row in set (0.00 sec)

MariaDB [(none)]> SELECT @@innodb_buffer_pool_instances;
+--------------------------------+
| @@innodb_buffer_pool_instances |
+--------------------------------+
|                              8 |
+--------------------------------+
1 row in set (0.00 sec)

MariaDB [(none)]> SELECT @@innodb_buffer_pool_chunk_size;
ERROR 1193 (HY000): Unknown system variable 'innodb_buffer_pool_chunk_size'
```

The innodb_buffer_pool_chunk_size not existing seems like it could be an issue too, but I'm not sure. I'll post more if I figure out a solution here.

**Comment by Jaace** [comment]
I've modified my local mysql.conf file in pilothouse by adding the following:
```
[mariadb]
innodb_file_format = barracuda

[mysqld]
...
innodb_log_file_size = 256M
```
I'm not sure that the innodb_file_format change is necessary but I added it in just in case. Now when booting up and looking through the container logs for pilothouse_mysql_1, I can see the change:
```
2017-02-26  0:33:08 140298783606720 [Note] InnoDB: Initializing buffer pool, size = 256.0M
2017-02-26  0:33:08 140298783606720 [Note] InnoDB: Completed initialization of buffer pool
2017-02-26  0:33:09 140298783606720 [Note] InnoDB: Highest supported file format is Barracuda.
2017-02-26  0:33:09 140298783606720 [Warning] InnoDB: Resizing redo log from 2*3072 to 2*16384 pages, LSN=12747169777
```

Running the large import (though I'm not sure the size mattered, just maybe one of the queries), now works fine. I'm no database configuration expert so if any of this is a red flag, let me know, otherwise I can make a PR.

**Comment by philipnewcomer** [comment]
I'm no database configuration expert either, so it'd be nice to have someone who knows more about this stuff weigh in on this issue. However, that's probably not going to happen, so in the meantime I'm good to have this added to the default mysql configuration file.

However, I would like to only add what's really needed, so if you're not sure that `innodb_file_format = barracuda` is required, let's do a bit of testing to verify that that's the case, and only add the `innodb_log_file_size` directive if possible.

**Comment by Jaace** [comment]
Absolutely agree. However, I did add some other items to my own config, referenced here, altered slightly for the 2Gb allotted to my Docker: https://github.com/million12/docker-mariadb/blob/master/container-files/etc/my.cnf.d/tuning.cnf

This brought times down quite a bit for queries. I had one select "LIKE" query that was taking around 150s brought down to 44.8s after using this config. Additionally, a wp-cli script to update across 30k posts was running at around 30 minutes - brought down to just over 5 minutes.

It'd be good to have some other eyes on this to vet what's necessary and what's pushing the limits of good practice.

**Comment by philipnewcomer** [comment]
I'm good to have those tuning parameters added in as well. It should help speed up our local sites. This config isn't intended for use in production environments anyway, so there shouldn't be a whole lot of fallout if something doesn't work as expected.

**Comment by Jaace** [comment]
Great! I can get a PR together tonight and send that over. I've been using these settings for a little over a week now with no issues.

**Comment by philipnewcomer** [comment]
Merged, thanks @Jaace!
