### ISSUE TITLE
Using XDebug for a CRON

### ISSUE THREAD

**Issue by Jaace** [Pilothouse-App/pilothouse#56]
This may be a misunderstanding of use on my part: I'm unable to get breakpoints to trigger for XDebug when the code I'm running is executed on a CRON.

I figured this is due to the XDebug setup using cookies that do not exist for the CRON when it's running in the background. Is there a setup that can be implemented to enable this, similar to how the wp-cli command needs a flag; something that can be set at the system level?

**Comment by philipnewcomer** [comment]
If the cron is triggered by WP calling itself, then I'm guessing even if xdebug is enabled for the original request, those cookies are not passed on to the second request.

Currently there's no way to enable xdebug when there is no cookie or query arg triggering it. Not sure how hard that would be to add.

You can, however, trigger a cron event manually from the command line with xdebug like this:
```
wp cron event run {event-name} --xdebug
```
