### ISSUE TITLE
sed: no such file or directory

### ISSUE THREAD

**Issue by AaronHolbrook** [Pilothouse-App/pilothouse#59]
FYI, ran into this on a fresh new site creation:

![](http://d.pr/i/f1UTv/4Zmgnw7i+)

**Comment by AaronHolbrook** [comment]
also wp did not install

**Comment by AaronHolbrook** [comment]
Ah, this is my fault; wp was not available via my PATH

**Comment by AaronHolbrook** [comment]
Actually it is available, not sure what's going on: 
![](http://d.pr/i/7CJPY/5rDZ8niZ+)

**Comment by philipnewcomer** [comment]
I think you need to run `composer install` in the PH directory. WP-CLI is installed via Composer and is then synced into the PHP containers.

**Comment by AaronHolbrook** [comment]
Ahhh, yea that did the trick
