### ISSUE TITLE
Formatting of wp-cli commands is unreadable

### ISSUE THREAD

**Issue by AaronHolbrook** [Pilothouse-App/pilothouse#65]
Not sure what can even be done here, but it used to work fine and is now looking like this: 

![](http://d.pr/i/nJ47R2/1psqKT3b+)

**Comment by philipnewcomer** [comment]
@AaronHolbrook did you resize your terminal window after initiating the command, but before the command displayed its output? I think that may have something to do with the borked formatting.

**Comment by philipnewcomer** [comment]
Possibly related: https://github.com/wp-cli/wp-cli/issues/4127

**Comment by AaronHolbrook** [comment]
This is not due to any resizing of the windows; any size window and not touching it before/during/after or at all still results in this mess. Are you able to replicate?

**Comment by AaronHolbrook** [comment]
Pulled latest and ran `composer update`; am now at wp cli version 1.2.1:

![](http://d.pr/i/WCYNkS/eUHw5ts9+)

Still busted

**Comment by Jaace** [comment]
This, feel, may be related to https://github.com/Pilothouse-App/pilothouse/issues/51 but I could be wrong.

**Comment by AaronHolbrook** [comment]
@Jaace are you also seeing the same issue?

**Comment by Jaace** [comment]
@AaronHolbrook I'm not seeing it that malformed but I am getting the tput issue.

**Comment by AaronHolbrook** [comment]
FYI i was getting the `tput: No such file..` way before i was getting malformed output

**Comment by philipnewcomer** [comment]
Yeah the `tput` issue has been there from the beginning.

@AaronHolbrook did you try rebuilding your Docker containers with the instructions I messaged you in Slack? I'm wondering if something that was installed in the container or some change might be doing this. I've not been able to reproduce it.

**Comment by markuswolff** [comment]
You might be missing the ncurses package. That would explain both the missing tput message and the broken formatting.

**Comment by philipnewcomer** [comment]
@AaronHolbrook I've added the `ncurses` package to the PHP docker images (#51). Run `pilothouse compose pull` to download the latest images, then `pilothouse down`, `pilothouse compose down` and `pilothouse restart` and see if that resolves your formatting issue.

**Comment by AaronHolbrook** [comment]
Do you want to update the composer wp-cli package also?

**Comment by AaronHolbrook** [comment]
Yes! This fixed it! 

![](http://d.pr/i/SaID4w/kxThxSB9+)

Thanks @markuswolff and @philipnewcomer !

**Comment by philipnewcomer** [comment]
Cool.

> Do you want to update the composer wp-cli package also?

Done in https://github.com/Pilothouse-App/pilothouse/commit/e9b1219eb76652048d9b910bea1c07ad6307178f

**Comment by AaronHolbrook** [comment]
Excellent!
