### ISSUE TITLE
Pilothouse disappears/stops running

### ISSUE THREAD

**Issue by AaronHolbrook** [Pilothouse-App/pilothouse#66]
Seems to happen after I leave my computer for a few minutes and come back, possibly a mac sleep issue, but I never have had any problems with dockerbox/pilothouse before.

I come back and the database and domains do not respond. 

Running `pilothouse up` gets everything going again, but I'm not sure what change has caused this to happen; it's quite annoying.

**Comment by philipnewcomer** [comment]
Do you by any chance have your IDE open, which may be paused on an Xdebug breakpoint triggered by having a wp-admin page open in your browser and doing an autosave or something?

If not, try restarting each of the containers individually to narrow down which one has paused, i.e. ph restart nginx/mysql/php70 etc.

**Comment by AaronHolbrook** [comment]
I do have an IDE open, but it is not paused at all. 

The computer definitely goes to sleep, but that was never an issue before. I'll try restarting each container next time

**Comment by philipnewcomer** [comment]
There's an update for Docker available, I didn't notice a fix for this issue specifically but updating might be worth a try.

**Comment by philipnewcomer** [comment]
@AaronHolbrook is this still happening after updating Docker?

**Comment by AaronHolbrook** [comment]
No, not as much
