### ISSUE TITLE
Convert Pilothouse script to NodeJS

### ISSUE THREAD

**Issue by philipnewcomer** [Pilothouse-App/pilothouse#68]
Rewrite the main `pilothouse` script in NodeJS instead of Bash. Among other benefits, Node will be overall easier and less obtuse to work with compared to Bash, and will make Pilothouse cross-platform with minimal effort.

**Comment by AaronHolbrook** [comment]
Won't that require a dev dependency of having node installed then? 

What about something like python instead?

**Comment by philipnewcomer** [comment]
Yes, it would require having Node installed. However, many developers, unless they only do backend work and never build frontend assets, already have it.

Unless things have changed on the Windows side, using Python instead would still require Windows users to install Python, so I don't see that Python would be any better from this perspective.

**Comment by philipnewcomer** [comment]
Merged to develop in e21795872aab1b171728bce0989b6a8ff70520f9

The NodeJS-based Pilothouse is ready for testing.
